#!/usr/bin/env python

"""
Wikigrouth command line corpus creation tool.

Example invocation:

$ wikigrouth file_containing_uris.txt
"""

import argparse
import sys

import wikigrouth

parser = argparse.ArgumentParser(
                    description="Aggregate corpus from given SKOS file.")
parser.add_argument('skosfile', type=str, nargs=1,
                    help="The input SKOS file.")
parser.add_argument('-f', '--force', action='store_true',
                    help="Force override")


if len(sys.argv) < 2:
    parser.print_help()
    sys.exit(1)

args = parser.parse_args()
wikigrouth.aggregate_corpus(args.skosfile[0], args.force)
