#!/usr/bin/env python

"""
Wikigrouth command line corpus creation tool.

Example invocation:

$ wikigrouth file_containing_uris.txt
"""

import argparse
import sys

import wikigrouth

parser = argparse.ArgumentParser(
                    description="Aggregate corpus from given seed file.")
parser.add_argument('seedfile', type=str, nargs=1,
                    help="The input seed file.")
parser.add_argument('-o', '--outputpath', type=str)
parser.add_argument('-f', '--force', action='store_true',
                    help="Force override")


if len(sys.argv) < 2:
    parser.print_help()
    sys.exit(1)

args = parser.parse_args()
wikigrouth.aggregate_corpus(args.seedfile[0], args.outputpath, args.force)
